services:
    web-server:
#        container_name: web-server
        build:
            dockerfile: ./.docker/httpd/Dockerfile
        ports:
            - "${FORWARD_SERVER_PORT:-8000}:80"
        volumes:
            - ./application:/var/www/html
    application:
#        container_name: application
        environment:
            MYSQL_HOST: "nette-di-example-database-1"
            MYSQL_PORT: 3306
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        build:
            dockerfile: ./.docker/php-fpm/Dockerfile
            target: base
            args:
                - UID=${UID:-1000}
                - GID=${GID:-1000}
        volumes:
            - ./.docker/php-fpm/conf/php.ini:/usr/local/etc/php/conf.d/php.ini:ro
            - ./application:/var/www/html
        extra_hosts:
            - "host.docker.internal:host-gateway"
        depends_on:
            - web-server
    database:
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
        image: mysql:8.4
        ports:
            - "${FORWARD_MYSQL_PORT:-3306}:3306"
        volumes:
            - mysqldata:/var/lib/mysql
        restart: unless-stopped
        command: [ "--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci" ]
    adminer:
        image: adminer:latest
        ports:
            - "${FORWARD_ADMINER_PORT:-8080}:8080"
        restart: unless-stopped
        depends_on:
            - database

volumes:
    mysqldata:
